### ISSUE TITLE
Jupyter notebook for Physion v1.5 OCP evaluation

### ISSUE THREAD

**Issue by duxiaodan** [neuroailab/CounterfactualWorldModels#11]
Dear authors,

I really like your CWM paper and would like to do some experiments with CWM models on the Physion v1.5 dataset. Could you please share a Jupyter notebook on how does one use CWM for Physionv1.5 prediction task? I'm not quite sure how to extract features of the stimulus video from CWM, e.g. how to pool the feature maps and how many frames to use etc.

Also, out of the three CWM ckpts you open-sourced, which one gives the best results on Physion?

Thank you very much

Xiaodan Du

**Comment by duxiaodan** [comment]
Sorry, didn't realize this is a different paper so closing

**Comment by honglin-chen** [comment]
Hi @duxiaodan, thank you for your interest in our work. We are actively working on the release of an updated codebase and the Physion v1.5 dataset. Stay tuned!
